family = "Inet" # Ip4 Ip6 or Inet for both , default Inet
table_name = "traffic_filter"
chain_name = "output_filter"
interface = "eth0" #  network interface to monitor
hook = "Output" # Input or Output  for traffic direction, default Output
priority =0  
policy = "Accept"
check_interval = 10
executor_pool_size =5 # nft subprocess  max size 
executor_max_age_secs = 300
executor_max_commands = 100
global_exclude = ["127.0.0.3"]

[[rules]]
window_secs = 20 # max 60
threshold_bps = 1_000_000
action = { Ban = { seconds = 5 } }
excluded_ips = ["127.0.0.2"]


[[rules]]
window_secs = 10
threshold_bps = 500_000
action = { RateLimit = { kbps = 100, burst = 10, seconds = 60} }
excluded_ips = ["::100:0"]