family = "Inet" # Ip4 Ip6 or Inet for both , default Inet
table_name = "traffic_filter"
chain_name = "output_chain"
interface = "eth0" #  network interface to monitor
hook = "Output" # Input or Output  for traffic direction, default Input

[[rules]]
window_secs = 20
threshold_bps = 10_000
action = { Ban = { seconds = 60 } }
excluded_ips = ["10.255.255.0"]


[[rules]]
window_secs = 10
threshold_bps = 5000
action = { RateLimit = { kbps = 1, burst = 1} }
excluded_ips = ["::100:0"]
        

